amqp:
  admin:
    auto-create: true
  host: localhost
  port: 5672
  username: adm_video
  password: 123456

mysql:
  username: root
  password: 123456
  schema: adm_videos
  url: localhost:3306

server:
  port: 8080
  undertow:
    threads:
      worker: 64 # Generally this should be reasonably high, at least 10 per CPU core: https://undertow.io/undertow-docs/undertow-docs-2.1.0/index.html#listeners-2
      io: 4 # One IO thread per CPU core is a reasonable default: https://undertow.io/undertow-docs/undertow-docs-2.1.0/index.html#listeners-2