name: CI/CD Pipeline

on:
  push:
    branches:
      - master
      - main
      - develop
      - stage
  # Habilita o gatinho manual através da interface do GitHub Actions
  workflow_dispatch:

env:
  IMAGE_NAME: pedromarsao/admin-do-catalogo

jobs:
  # Job para execução dos testes
  tests:
    name: Tests runner
    runs-on: ubuntu-latest
    # Configuração dos passos do job
    steps:
      # 1. Passo para fazer checkout do código
      - uses: actions/checkout@v3
      # 2. Passo para configurar a JDK na versão 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      # 3. Passo para executar os testes usando Gradle
      - name: Run applications tests
        run: ./gradlew test

  #job para build e deploy da aplicação
  build:
    name: Build runner
    needs: tests
    runs-on: ubuntu-latest
    steps:
      # 1. Passo para fazer checkout do código
      - uses: actions/checkout@v3
      # 2. Passo para configurar a JDK na versão 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      # 3. Valida a existência do gradle wrapper
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      # 4. Realizar o build para pegar o artefato da acplicação
      - name: Build application
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: clean build -x test
      # 5. Definir variável branch name
      - name: Set BUILD_TAG
        run: |
          echo BUILD_TAG=$(echo ${{ github.head_ref || github.ref_name }} | sed "s,/,_,g")-${{ github.run_number }} >> $GITHUB_ENV
      # 6. Print BUILD_TAG
      - name: Print BUILD_TAG defined
        run: |
          echo "Branch     ---> ${{ github.head_ref || github.ref_name }}"
          echo "Run number ---> ${{ github.run_number }}"
          echo "Tag        ---> ${{ env.BUILD_TAG }}"
      # 7. Login no Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PWD }}
      # 8. Build e push da imagem Docker
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          build-args: VERSION=${{ env.BUILD_TAG }}
          tags: ${{ env.IMAGE_NAME }}:${{ env.BUILD_TAG }}
